edition = "2021"
use_field_init_shorthand = true
use_try_shorthand = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Upper"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
unstable_features = true
version = "Two"
